{{- if .Values.gateway.enabled -}}
{{- $fullName := include "dead-drop.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $gateway := cat $fullName "-gateway" -}}
{{- if .Values.gateway.clusterGateway -}}
{{- $gateway = .Values.gateway.clusterGateway -}}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "dead-drop.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- range .Values.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  - name: {{ $gateway }}
    port: 80
    {{- if .Values.gateway.clusterGatewayNamespace }}
    namespace: {{ .Values.gateway.clusterGatewayNamespace  }}
    {{- end }}
  rules:
  - filters:
    - requestRedirect:
        scheme: https
        statusCode: 308
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents: null
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-https
  labels:
    {{- include "dead-drop.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- range .Values.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  - name: {{ $gateway }}
    {{- if .Values.gateway.clusterGatewayNamespace }}
    namespace: {{ .Values.gateway.clusterGatewayNamespace  }}
    {{- end }}
    port: 443
  rules:
  - backendRefs:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents: []
{{- end }}
