apiVersion: v1
kind: Service
metadata:
  name: {{ include "dead-drop.fullname" . }}
  labels:
    {{- include "dead-drop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    {{- include "dead-drop.selectorLabels" . | nindent 4 }}
